In [1]:
import requests
import pandas as pd
import time

In [48]:
import requests

API_KEY = "c5429ff7cemshbc766a1e1332931p191b95jsn2a776659c726"
HOST = "axesso-axesso-amazon-data-service-v1.p.rapidapi.com"

url = "https://axesso-axesso-amazon-data-service-v1.p.rapidapi.com/amz/amazon-search-by-keyword-asin"

headers = {
    "x-rapidapi-key": API_KEY,
    "x-rapidapi-host": HOST
}

params = {
    "keyword": "board game",
    "page": "1",
    "domainCode": "com",
    "excludeSponsored": "false",
    "sortBy": "relevanceblender",
    "withCache": "true"
}

response = requests.get(url, headers=headers, params=params)

print("Status:", response.status_code)

data = response.json()

print("\nTop-level keys:")
print(data.keys())

print("\nResponse message (important):")
print(data.get("responseMessage"))

Status: 200

Top-level keys:
dict_keys(['responseStatus', 'responseMessage', 'sortStrategy', 'domainCode', 'keyword', 'numberOfProducts', 'numberOfSponsoredProducts', 'resultCount', 'currentPage', 'lastPage', 'selectedCategory', 'foundSponsoredProducts', 'foundProducts', 'searchProductDetails', 'categories', 'starFilterParam', 'similarKeywords', 'browseNode', 'nodeHierarchy'])

Response message (important):
Product successfully found!

In [49]:
products = data.get("searchProductDetails")

print("Number of products:", len(products))
print(products[0])

Number of products: 48
{'productDescription': 'Sorry! Board Game for Kids Ages 6 and Up; Classic Hasbro Board Game; Each Player Gets 4 Pawns; Family Game', 'asin': 'B076HK9H7Z', 'countReview': 33742, 'imgUrl': 'https://m.media-amazon.com/images/I/81CA3GV9sXL._AC_UL320_.jpg', 'price': 8.98, 'retailPrice': 9.99, 'productRating': '4.8 out of 5 stars', 'prime': False, 'dpUrl': '/Hasbro-Gaming-A5065-Sorry-Game/dp/B076HK9H7Z/ref=sr_1_1?dib=eyJ2IjoiMSJ9.gbrrvDNTxqSRV54M2PPTkMUaNxlnGKJG1k2FO70rn2LkBOuTLyPOTchupFxXoALb3wdgze516UpPG7EjB44t2QREaGSmJ1ensloRm7HqKYQojQzRs5IBDmL6D9E7mxkDjI2ZBpYVNgCT5EPYK5KSDmAuBnA9DP6TR2vhw66FpQGUyv6gM6xl9FOxpYjp7DoFG4NeiEnErTXOwsc1q_DS8sg5R3xkxWxoiLxmJGGlxly2OUa4pcHlZ7Tj2lcLHZ84d8Q6RH_bvM5HfPyjbGLRqARcpq3F1r2iwQGdyFsWdz4.8i8PO7LJnELcF0g9A9ZXqrGytG-qp7LfP-4jm8r9yms&dib_tag=se&keywords=board+game&qid=1776691428&sr=8-1', 'series': None, 'deliveryMessage': 'FREE delivery Sat, Apr 25 on $35 of items shipped by Amazon', 'variations': [], 'productDetails': [], 'salesVolume': '10K+ bought in past month', 'manufacturer': None, 'secondaryOffer': 0.0}

In [50]:
products = data["searchProductDetails"]

print("Number of products:", len(products))
print(products[0])

Number of products: 48
{'productDescription': 'Sorry! Board Game for Kids Ages 6 and Up; Classic Hasbro Board Game; Each Player Gets 4 Pawns; Family Game', 'asin': 'B076HK9H7Z', 'countReview': 33742, 'imgUrl': 'https://m.media-amazon.com/images/I/81CA3GV9sXL._AC_UL320_.jpg', 'price': 8.98, 'retailPrice': 9.99, 'productRating': '4.8 out of 5 stars', 'prime': False, 'dpUrl': '/Hasbro-Gaming-A5065-Sorry-Game/dp/B076HK9H7Z/ref=sr_1_1?dib=eyJ2IjoiMSJ9.gbrrvDNTxqSRV54M2PPTkMUaNxlnGKJG1k2FO70rn2LkBOuTLyPOTchupFxXoALb3wdgze516UpPG7EjB44t2QREaGSmJ1ensloRm7HqKYQojQzRs5IBDmL6D9E7mxkDjI2ZBpYVNgCT5EPYK5KSDmAuBnA9DP6TR2vhw66FpQGUyv6gM6xl9FOxpYjp7DoFG4NeiEnErTXOwsc1q_DS8sg5R3xkxWxoiLxmJGGlxly2OUa4pcHlZ7Tj2lcLHZ84d8Q6RH_bvM5HfPyjbGLRqARcpq3F1r2iwQGdyFsWdz4.8i8PO7LJnELcF0g9A9ZXqrGytG-qp7LfP-4jm8r9yms&dib_tag=se&keywords=board+game&qid=1776691428&sr=8-1', 'series': None, 'deliveryMessage': 'FREE delivery Sat, Apr 25 on $35 of items shipped by Amazon', 'variations': [], 'productDetails': [], 'salesVolume': '10K+ bought in past month', 'manufacturer': None, 'secondaryOffer': 0.0}

In [51]:
df = pd.DataFrame(products)

In [52]:
df.head()
df.shape
df.columns

Index(['productDescription', 'asin', 'countReview', 'imgUrl', 'price',
       'retailPrice', 'productRating', 'prime', 'dpUrl', 'series',
       'deliveryMessage', 'variations', 'productDetails', 'salesVolume',
       'manufacturer', 'secondaryOffer'],
      dtype='object')

In [53]:
categories = ["board game", "coffee beans", "non-fiction book"]

In [54]:
all_products = []

In [56]:
for category in categories:
    print(f"Fetching: {category}")
    
    params = {
        "keyword": category,
        "page": "1",
        "domainCode": "com",
        "excludeSponsored": "false",
        "sortBy": "relevanceblender",
        "withCache": "true"
    }

    response = requests.get(url, headers=headers, params=params)
    
    print("Status:", response.status_code)
    
    data = response.json()
    
    products = data.get("searchProductDetails", [])
    
    print("Products found:", len(products))
    
    for p in products:
        p["category"] = category   # label each row
        all_products.append(p)

    time.sleep(1)

Fetching: board game
Status: 200
Products found: 48
Fetching: coffee beans
Status: 200
Products found: 48
Fetching: non-fiction book
Status: 200
Products found: 16

In [57]:
categories = ["board game", "coffee beans", "wireless headphones"]

In [58]:
all_products = []

for category in categories:
    print(f"\nFetching: {category}")
    
    for page in range(1, 3):  # 2 pages per category is usually enough for free tier
        print(f"Page: {page}")
        
        params = {
            "keyword": category,
            "page": str(page),
            "domainCode": "com",
            "excludeSponsored": "false",
            "sortBy": "relevanceblender",
            "withCache": "true"
        }

        response = requests.get(url, headers=headers, params=params)
        
        print("Status:", response.status_code)
        
        data = response.json()
        
        products = data.get("searchProductDetails", [])
        
        print("Products found:", len(products))
        
        for p in products:
            p["category"] = category
            all_products.append(p)

        time.sleep(1)

Fetching: board game
Page: 1
Status: 200
Products found: 48
Page: 2
Status: 200
Products found: 48

Fetching: coffee beans
Page: 1
Status: 200
Products found: 48
Page: 2
Status: 200
Products found: 48

Fetching: wireless headphones
Page: 1
Status: 200
Products found: 16
Page: 2
Status: 200
Products found: 16

In [59]:
df = pd.DataFrame(all_products)

In [60]:
df.shape

(224, 17)

In [61]:
df["category"].value_counts()

category
board game             96
coffee beans           96
wireless headphones    32
Name: count, dtype: int64

In [62]:
df.columns

Index(['productDescription', 'asin', 'countReview', 'imgUrl', 'price',
       'retailPrice', 'productRating', 'prime', 'dpUrl', 'series',
       'deliveryMessage', 'variations', 'productDetails', 'salesVolume',
       'manufacturer', 'secondaryOffer', 'category'],
      dtype='object')

In [63]:
df.head()

,productDescription,asin,countReview,imgUrl,price,retailPrice,productRating,prime,dpUrl,series,deliveryMessage,variations,productDetails,salesVolume,manufacturer,secondaryOffer,category
0,"CATAN Board Game (6th Edition) Trade, Build & ...",B0DYK1ZH2D,39443,https://m.media-amazon.com/images/I/71AbDpYEkg...,41.99,43.99,4.8 out of 5 stars,False,/CATAN-Classic-Strategy-Players-Playtime/dp/B0...,None,"FREE delivery Sat, Apr 25",[],[],6K+ bought in past month,None,0.00,board game
1,"Hasbro Gaming Connect 4 Classic Grid, 4 in a R...",B00D8STBHY,81275,https://m.media-amazon.com/images/I/81fEiLrmZ8...,8.89,9.99,4.8 out of 5 stars,False,/Hasbro-A5640-Connect-4-Game/dp/B00D8STBHY/ref...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,0.00,board game
2,Sorry! Board Game for Kids Ages 6 and Up; Clas...,B076HK9H7Z,33742,https://m.media-amazon.com/images/I/81CA3GV9sX...,8.98,9.99,4.8 out of 5 stars,False,/Hasbro-Gaming-A5065-Sorry-Game/dp/B076HK9H7Z/...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,0.00,board game
3,HUES and CUES - Vibrant Color Guessing Board G...,B084D2XQ9F,9848,https://m.media-amazon.com/images/I/81WUD2cZo5...,24.95,0.00,4.7 out of 5 stars,False,/USAOPOLY-Vibrant-Guessing-Perfect-Together/dp...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],8K+ bought in past month,None,22.07,board game
4,Hasbro Gaming Candy Land Kingdom of Sweet Adve...,B00000DMF5,37195,https://m.media-amazon.com/images/I/71ZnGyItfo...,12.99,0.00,4.8 out of 5 stars,False,/Hasbro-Gaming-Kingdom-Adventures-Exclusive/dp...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,0.00,board game

In [64]:
df.to_csv("raw_amazon_products.csv", index=False)

In [65]:
df.dtypes

productDescription     object
asin                   object
countReview             int64
imgUrl                 object
price                 float64
retailPrice           float64
productRating          object
prime                    bool
dpUrl                  object
series                 object
deliveryMessage        object
variations             object
productDetails         object
salesVolume            object
manufacturer           object
secondaryOffer        float64
category               object
dtype: object

In [66]:
df.isnull().sum().sort_values(ascending=False)

series                224
manufacturer          224
salesVolume             5
deliveryMessage         5
productRating           1
productDescription      0
secondaryOffer          0
productDetails          0
variations              0
dpUrl                   0
asin                    0
prime                   0
retailPrice             0
price                   0
imgUrl                  0
countReview             0
category                0
dtype: int64

In [67]:
df = pd.DataFrame(all_products)

In [68]:
df.describe(include="all")

,productDescription,asin,countReview,imgUrl,price,retailPrice,productRating,prime,dpUrl,series,deliveryMessage,variations,productDetails,salesVolume,manufacturer,secondaryOffer,category
count,224,224,224.000000,224,224.000000,224.000000,223,224,224,0,219,224,224,219,0,224.000000,224
unique,211,211,NaN,211,NaN,NaN,11,1,224,0,15,1,1,25,0,NaN,3
top,"Starbucks Whole Coffee Beans, Starbucks Blonde...",B01EYCIBZ0,NaN,https://m.media-amazon.com/images/I/71-NaDZz5Z...,NaN,NaN,4.6 out of 5 stars,False,/CATAN-Classic-Strategy-Players-Playtime/dp/B0...,NaN,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],1K+ bought in past month,NaN,NaN,board game
freq,2,2,NaN,2,NaN,NaN,50,224,1,NaN,147,224,224,48,NaN,NaN,96
mean,NaN,NaN,10336.026786,NaN,34.678259,20.060045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.382991,NaN
std,NaN,NaN,18029.451366,NaN,42.528077,44.181358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.350988,NaN
min,NaN,NaN,0.000000,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
25%,NaN,NaN,800.500000,NaN,16.855000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
50%,NaN,NaN,3143.000000,NaN,23.295000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN
75%,NaN,NaN,11547.750000,NaN,36.480000,24.990000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.982500,NaN
max,NaN,NaN,116641.000000,NaN,359.000000,299.990000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,279.990000,NaN

In [69]:
import numpy as np

df["price"] = df["price"].replace(0, np.nan)

In [70]:
df

,productDescription,asin,countReview,imgUrl,price,retailPrice,productRating,prime,dpUrl,series,deliveryMessage,variations,productDetails,salesVolume,manufacturer,secondaryOffer,category
0,"CATAN Board Game (6th Edition) Trade, Build & ...",B0DYK1ZH2D,39443,https://m.media-amazon.com/images/I/71AbDpYEkg...,41.99,43.99,4.8 out of 5 stars,False,/CATAN-Classic-Strategy-Players-Playtime/dp/B0...,None,"FREE delivery Sat, Apr 25",[],[],6K+ bought in past month,None,0.00,board game
1,"Hasbro Gaming Connect 4 Classic Grid, 4 in a R...",B00D8STBHY,81275,https://m.media-amazon.com/images/I/81fEiLrmZ8...,8.89,9.99,4.8 out of 5 stars,False,/Hasbro-A5640-Connect-4-Game/dp/B00D8STBHY/ref...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,0.00,board game
2,Sorry! Board Game for Kids Ages 6 and Up; Clas...,B076HK9H7Z,33742,https://m.media-amazon.com/images/I/81CA3GV9sX...,8.98,9.99,4.8 out of 5 stars,False,/Hasbro-Gaming-A5065-Sorry-Game/dp/B076HK9H7Z/...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,0.00,board game
3,HUES and CUES - Vibrant Color Guessing Board G...,B084D2XQ9F,9848,https://m.media-amazon.com/images/I/81WUD2cZo5...,24.95,0.00,4.7 out of 5 stars,False,/USAOPOLY-Vibrant-Guessing-Perfect-Together/dp...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],8K+ bought in past month,None,22.07,board game
4,Hasbro Gaming Candy Land Kingdom of Sweet Adve...,B00000DMF5,37195,https://m.media-amazon.com/images/I/71ZnGyItfo...,12.99,0.00,4.8 out of 5 stars,False,/Hasbro-Gaming-Kingdom-Adventures-Exclusive/dp...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,0.00,board game
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,"Uliptz Wireless Bluetooth Headphones, 65H Play...",B09NNBBY8F,14192,https://m.media-amazon.com/images/I/61-ZTbzw6o...,15.99,19.99,4.6 out of 5 stars,False,/Uliptz-Bluetooth-Headphones-Microphone-Lightw...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,0.00,wireless headphones
220,Beats Studio Pro - Premium Wireless Over-Ear H...,B0FHM61VTK,26990,https://m.media-amazon.com/images/I/61c8vBJoCm...,349.95,0.00,4.5 out of 5 stars,False,/Beats-Studio-Pro-Headphones-Cancelling/dp/B0F...,None,"FREE delivery Sat, Apr 25",[],[],7K+ bought in past month,None,139.28,wireless headphones
221,Avantree Opera - Wireless Headphones for TV Wa...,B08D6GHYD7,5268,https://m.media-amazon.com/images/I/61s3zJjDdt...,149.99,159.99,4.2 out of 5 stars,False,/Avantree-Wireless-Headphones-Transmitter-Blue...,None,"FREE delivery Sat, Apr 25",[],[],None,None,0.00,wireless headphones
222,bmani Ear Buds Wireless Earbuds Bluetooth Head...,B09FLNSYDZ,53452,https://m.media-amazon.com/images/I/71GPFE2yHG...,24.67,39.99,4.4 out of 5 stars,False,/Wireless-Bluetooth-Headphones-Earphones-BMANI...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,23.44,wireless headphones
223,JOYWISE Bluetooth Wireless Headphones 16H Play...,B0BTLVHMHW,3094,https://m.media-amazon.com/images/I/61y8xIywvg...,19.99,27.99,4.4 out of 5 stars,False,/JOYWISE-Bluetooth-Headphones-Earphones-Waterp...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],2K+ bought in past month,None,15.08,wireless headphones

In [71]:
df["price"].describe()

count    218.000000
mean      35.632706
std       42.713926
min        4.990000
25%       16.990000
50%       24.335000
75%       37.987500
max      359.000000
Name: price, dtype: float64

In [72]:
df["price"].isnull().sum()

np.int64(6)

In [73]:
df.sample(20)

,productDescription,asin,countReview,imgUrl,price,retailPrice,productRating,prime,dpUrl,series,deliveryMessage,variations,productDetails,salesVolume,manufacturer,secondaryOffer,category
107,"Starbucks Whole Bean Coffee, Dark Roast Coffee...",B0959PRQG8,4932,https://m.media-amazon.com/images/I/71IoLTQ6Pj...,23.19,0.00,4.6 out of 5 stars,False,/Starbucks-Coffee-French-Arabica-ounces/dp/B09...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],9K+ bought in past month,None,0.00,coffee beans
222,bmani Ear Buds Wireless Earbuds Bluetooth Head...,B09FLNSYDZ,53452,https://m.media-amazon.com/images/I/71GPFE2yHG...,24.67,39.99,4.4 out of 5 stars,False,/Wireless-Bluetooth-Headphones-Earphones-BMANI...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,23.44,wireless headphones
215,Bluetooth Headphones with Active Noise Cancell...,B0GLN8R9D7,25,https://m.media-amazon.com/images/I/61O-+3Hbvh...,16.99,19.99,4.3 out of 5 stars,False,/MMWOWARTS-Bluetooth-Headphones-Cancelling-Wir...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],1K+ bought in past month,None,0.00,wireless headphones
145,"BROOKLYN COFFEE Whole Bean, Italian Dark Roast...",B07K9GHM42,4758,https://m.media-amazon.com/images/I/71QhpYGr5O...,29.99,0.00,4.5 out of 5 stars,False,/Italian-Classic-Breakfast-Gourmet-Espresso/dp...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],600+ bought in past month,None,0.00,coffee beans
6,"Mattel Games UNO Card Game for Kid, Adult & Fa...",B07P6MZPK3,60178,https://m.media-amazon.com/images/I/81tVL-E4lk...,11.87,0.00,4.8 out of 5 stars,False,/Mattel-Games-Collectible-Families-Exclusive/d...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,10.12,board game
129,Dunkin' Original Blend Medium Roast Whole Bean...,B07C55PQLW,1133,https://m.media-amazon.com/images/I/81vBWrKMFy...,58.00,0.00,4.7 out of 5 stars,False,/Dunkin-Donuts-Original-Coffee-Medium/dp/B07C5...,None,FREE delivery Apr 23 - 24,[],[],2K+ bought in past month,None,55.99,coffee beans
175,COUNTER CULTURE COFFEE Organic Fast Forward Wh...,B0C384592F,78,https://m.media-amazon.com/images/I/719aM4IWCG...,28.49,0.00,4.6 out of 5 stars,False,/Counter-Culture-Coffee-Organic-Forward/dp/B0C...,None,$9.95 delivery Today 2 PM - 4 PM with Prime,[],[],1K+ bought in past month,None,0.00,coffee beans
166,"Peet's Coffee, Medium Roast Whole Bean Coffee,...",B08H2QBTN6,787,https://m.media-amazon.com/images/I/71e420X0Ba...,65.94,72.99,4.6 out of 5 stars,False,/Peets-Coffee-Medium-Roast-Ground/dp/B08H2QBTN...,None,"FREE delivery Sat, Apr 25",[],[],800+ bought in past month,None,0.00,coffee beans
48,Horrible Therapist: Extra Horrible Edition by ...,B0D2JG7873,2533,https://m.media-amazon.com/images/I/81bxkboACm...,24.97,0.00,4.5 out of 5 stars,False,/Exploding-Kittens-Horrible-Therapist-Unpleasa...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],2K+ bought in past month,None,0.00,board game
149,Ruta Maya Organic Medium Roast Whole Bean Coff...,B005UHP792,147,https://m.media-amazon.com/images/I/61LfEYHol9...,52.90,0.00,4.6 out of 5 stars,False,/Ruta-Maya%C2%AE-Organic-Medium-Coffee/dp/B005...,None,"FREE delivery Wed, Apr 22",[],[],800+ bought in past month,None,48.86,coffee beans
42,"Hasbro Gaming Guess Who? Board Game, with Peop...",B08MVWB4SC,6784,https://m.media-amazon.com/images/I/81mFyh0CKQ...,17.00,0.00,4.6 out of 5 stars,False,/Hasbro-Gaming-People-Original-Guessing/dp/B08...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],4K+ bought in past month,None,0.00,board game
152,Don Pablo Gourmet Coffee - Signature Blend - M...,B00CZ2KYRU,9527,https://m.media-amazon.com/images/I/91+F4s1-gU...,32.99,0.00,4.6 out of 5 stars,False,/Cafe-Don-Pablo-Gourmet-Signature/dp/B00CZ2KYR...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],800+ bought in past month,None,31.99,coffee beans
197,"BERIBES Bluetooth Headphones Over Ear, 65H Pla...",B09LYF2ST7,53370,https://m.media-amazon.com/images/I/71F2ccIPPL...,19.99,28.99,4.5 out of 5 stars,False,/BERIBES-Bluetooth-Headphones-Microphone-Light...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,0.00,wireless headphones
70,"Farkle Classic Dice Game – Rainbow Kids Games,...",B0DH9KN56R,175,https://m.media-amazon.com/images/I/51JBVtCknq...,4.99,0.00,4.7 out of 5 stars,False,/Farkle-Classic-Dice-Game-Included/dp/B0DH9KN5...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],2K+ bought in past month,None,0.00,board game
21,"Spin Master Games, Hedbanz 2023 Edition with N...",B0BRYH5FJ8,15500,https://m.media-amazon.com/images/I/81SYDKizNo...,15.99,17.99,4.7 out of 5 stars,False,/Hedbanz-Picture-Guessing-Games-Families/dp/B0...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,14.64,board game
46,Horrible Therapist: Extra Horrible Edition by ...,B0D2JG7873,2533,https://m.media-amazon.com/images/I/81bxkboACm...,24.97,0.00,4.5 out of 5 stars,False,/Exploding-Kittens-Horrible-Therapist-Unpleasa...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],2K+ bought in past month,None,0.00,board game
56,Hasbro Gaming Jenga Wooden Blocks Stacking Tum...,B000GBA60W,23692,https://m.media-amazon.com/images/I/815ZoU2clx...,19.99,0.00,4.8 out of 5 stars,False,/Wooden-Blocks-Stacking-Tumbling-Exclusive/dp/...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],3K+ bought in past month,None,0.00,board game
18,Monopoly Board Game | Classic Game with Storag...,B0DN37BBGD,1244,https://m.media-amazon.com/images/I/71DVm2JkLR...,14.99,19.99,4.8 out of 5 stars,False,/Monopoly-Classic-Storage-Larger-Players/dp/B0...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],3K+ bought in past month,None,13.73,board game
14,"Monopoly Game, Family Board Games for 2 to 6 P...",B0B5HLZ8T4,5534,https://m.media-amazon.com/images/I/816dE7TY9x...,19.95,0.00,4.8 out of 5 stars,False,/Monopoly-Family-Board-Players-Tokens/dp/B0B5H...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,0.00,board game
218,JBL Tune 510BT - Bluetooth headphones with up ...,B092CP8ZH4,90693,https://m.media-amazon.com/images/I/51Dd8aGSW0...,NaN,0.00,4.5 out of 5 stars,False,/JBL-Tune-510BT-Ear-Headphones/dp/B092CP8ZH4/r...,None,None,[],[],10K+ bought in past month,None,0.00,wireless headphones

In [74]:
df.sample(20, random_state=42)

,productDescription,asin,countReview,imgUrl,price,retailPrice,productRating,prime,dpUrl,series,deliveryMessage,variations,productDetails,salesVolume,manufacturer,secondaryOffer,category
9,Hasbro Gaming Battleship Classic Board Game | ...,B09D4QRJ8Y,7624,https://m.media-amazon.com/images/I/81PXMzof4N...,16.84,19.99,4.7 out of 5 stars,False,/Battleship-Classic-Board-Strategy-Players/dp/...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,0.00,board game
84,Mouse Trap Board Game For Kids Ages 6 and Up (...,B00000DMFD,9324,https://m.media-amazon.com/images/I/81imYb-vUp...,24.99,0.00,4.6 out of 5 stars,False,/Mouse-Trap-Game-Amazon-Exclusive/dp/B00000DMF...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],1K+ bought in past month,None,0.00,board game
117,"Starbucks Whole Coffee Beans, Medium Roast Hot...",B07LFSNK9M,1837,https://m.media-amazon.com/images/I/8145WujhgP...,30.42,32.07,4.7 out of 5 stars,False,/Starbucks-Medium-Coffee-Variety-12-oz/dp/B07L...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],800+ bought in past month,None,0.00,coffee beans
144,"365 by Whole Foods Market, Pleasant Morning Bu...",B074XXNDRC,1838,https://m.media-amazon.com/images/I/61qfanxE-f...,18.48,0.00,4.2 out of 5 stars,False,/365-Whole-Foods-Market-Medium-Dark/dp/B074XXN...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],2K+ bought in past month,None,0.00,coffee beans
221,Avantree Opera - Wireless Headphones for TV Wa...,B08D6GHYD7,5268,https://m.media-amazon.com/images/I/61s3zJjDdt...,149.99,159.99,4.2 out of 5 stars,False,/Avantree-Wireless-Headphones-Transmitter-Blue...,None,"FREE delivery Sat, Apr 25",[],[],None,None,0.00,wireless headphones
113,"Copper Moon Dark Roast Whole Bean Coffee, Suma...",B01L9YE808,5818,https://m.media-amazon.com/images/I/71PI8ZHsSw...,21.49,0.00,4.4 out of 5 stars,False,/Copper-Moon-Sumatra-Smoothly-Full-Bodied/dp/B...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],7K+ bought in past month,None,0.00,coffee beans
68,Spooktacular Board Game – Play as 20 Spooky Ci...,B0F16HLC5P,18,https://m.media-amazon.com/images/I/716aHggtCv...,59.99,0.00,4.7 out of 5 stars,False,/Spooktacular-Board-Game-Monsters-Strategy/dp/...,None,"FREE delivery Sat, Apr 25",[],[],50+ bought in past month,None,0.00,board game
104,Amazon Fresh Organic Fair Trade Sumatra Whole ...,B072MQFGHG,1863,https://m.media-amazon.com/images/I/81VE86P+G1...,6.98,0.00,4.2 out of 5 stars,False,/AmazonFresh-Organic-Trade-Sumatra-Coffee/dp/B...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,0.00,coffee beans
177,"Tony's Coffee, Cafe Carmelita (12oz), Medium R...",B01I93B9GI,148,https://m.media-amazon.com/images/I/61kn2JnLg2...,NaN,0.00,4.6 out of 5 stars,False,/Tonys-Coffee-Cafe-Carmelita-Whole/dp/B01I93B9...,None,None,[],[],200+ bought in past month,None,18.50,coffee beans
185,"365 by Whole Foods Market, Island Blend Whole ...",B074H81M7Y,478,https://m.media-amazon.com/images/I/61hoFRHIL3...,18.48,0.00,4.5 out of 5 stars,False,/365-Whole-Foods-Market-Medium-Light/dp/B074H8...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],700+ bought in past month,None,0.00,coffee beans
55,The Night Cage by Smirk and Dagger | Cooperati...,B08ZSK752P,879,https://m.media-amazon.com/images/I/61KfSCGnpB...,38.52,44.99,4.7 out of 5 stars,False,/Smirk-Dagger-The-Night-Cage/dp/B08ZSK752P/ref...,None,"FREE delivery Sat, Apr 25",[],[],200+ bought in past month,None,32.22,board game
15,Taco Cat Goat Cheese Pizza Wildly Entertaining...,B077Z1R28P,53337,https://m.media-amazon.com/images/I/61L3JcwfsD...,8.10,9.99,4.8 out of 5 stars,False,/Taco-Cat-Goat-Cheese-Pizza/dp/B077Z1R28P/ref=...,None,FREE delivery Apr 22 - 24,[],[],10K+ bought in past month,None,0.00,board game
199,Sony WH-CH520 Wireless Headphones Bluetooth On...,B0BS1RT9S2,31333,https://m.media-amazon.com/images/I/41JACWT-wW...,38.00,69.99,4.5 out of 5 stars,False,/Sony-WH-CH520-Headphones-Bluetooth-Microphone...,None,"FREE delivery Sat, Apr 25",[],[],4K+ bought in past month,None,32.43,wireless headphones
25,Secret Hitler,B01JKD4HYC,15015,https://m.media-amazon.com/images/I/51FQfTXB+H...,45.00,0.00,4.9 out of 5 stars,False,/Secret-Hitler/dp/B01JKD4HYC/ref=sr_1_26?dib=e...,None,"FREE delivery Sat, Apr 25",[],[],3K+ bought in past month,None,0.00,board game
30,"Hasbro® Don’t Break The Ice Game, Classic Vers...",B01MS6B7BV,18044,https://m.media-amazon.com/images/I/81KhN-wJEW...,17.35,19.99,4.8 out of 5 stars,False,/Dont-Break-the-Ice-Game/dp/B01MS6B7BV/ref=sr_...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,0.00,board game
45,Lucky Egg Official Grab The Mic – Family Karao...,B0CWVMNNFV,3979,https://m.media-amazon.com/images/I/71lzGgv9hk...,19.99,0.00,4.7 out of 5 stars,False,/Lucky-Egg-Exciting-Grab-Mic/dp/B0CWVMNNFV/ref...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],7K+ bought in past month,None,0.00,board game
171,"Lavazza Espresso Whole Bean Coffee, Medium Roa...",B016RY0LWO,6804,https://m.media-amazon.com/images/I/61DZrxomt+...,25.90,0.00,4.7 out of 5 stars,False,/Lavazza-Espresso-Coffee-Medium-2-2-Pound/dp/B...,None,"FREE delivery Mon, Apr 27",[],[],10K+ bought in past month,None,24.00,coffee beans
82,Asmodee HEAT: Pedal to the Metal Board Game - ...,B0BGXPZG4B,924,https://m.media-amazon.com/images/I/91v-6pjK0Z...,67.49,74.99,4.8 out of 5 stars,False,/Strategy-Players-Playtime-Days-Wonder/dp/B0BG...,None,"FREE delivery Sat, Apr 25",[],[],500+ bought in past month,None,61.42,board game
208,"JBL Tune 520BT - Wireless On-Ear Headphones, U...",B0CQ1HP3RX,13697,https://m.media-amazon.com/images/I/61mz7Wxnjd...,39.95,59.95,4.6 out of 5 stars,False,/JBL-Tune-520BT-Ear-Lightweight/dp/B0CQ1HP3RX/...,None,"FREE delivery Sat, Apr 25",[],[],2K+ bought in past month,None,37.95,wireless headphones
97,"Amazon Fresh, Colombia Whole Bean Coffee Mediu...",B071WWCVJV,11459,https://m.media-amazon.com/images/I/7121M8H6is...,18.37,0.00,4.3 out of 5 stars,False,/AmazonFresh-Colombia-Whole-Coffee-Medium/dp/B...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],20K+ bought in past month,None,0.00,coffee beans

In [75]:
df.head(20)
df.tail(20)

,productDescription,asin,countReview,imgUrl,price,retailPrice,productRating,prime,dpUrl,series,deliveryMessage,variations,productDetails,salesVolume,manufacturer,secondaryOffer,category
204,Hybrid Active Noise Cancelling Headphones 120H...,B0GSD4KRC3,86,https://m.media-amazon.com/images/I/71+gY7nhqu...,89.99,199.99,5.0 out of 5 stars,False,/Cancelling-Headphones-Playtime-Bluetooth-Head...,None,"FREE delivery Sat, Apr 25",[],[],2K+ bought in past month,None,35.99,wireless headphones
205,"KVIDIO Bluetooth Headphones Over Ear, 65 Hours...",B09BF64J55,32757,https://m.media-amazon.com/images/I/71Hx8b6HGb...,18.99,24.56,4.5 out of 5 stars,False,/Bluetooth-Headphones-KVIDIO-Microphone-Lightw...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,0.00,wireless headphones
206,Sony WH-CH720N Noise Canceling Wireless Headph...,B0BS1QCFHX,15036,https://m.media-amazon.com/images/I/51rpbVmi9X...,98.00,179.99,4.4 out of 5 stars,False,/Sony-WH-CH720N-Canceling-Headphones-Microphon...,None,"FREE delivery Tomorrow, Apr 21",[],[],7K+ bought in past month,None,65.00,wireless headphones
207,Beats Solo 4 - Wireless On-Ear Bluetooth Headp...,B0CZPLV566,25024,https://m.media-amazon.com/images/I/515FE+S4yL...,149.95,199.95,4.6 out of 5 stars,False,/Beats-Solo-Wireless-Headphones-Matte/dp/B0CZP...,None,"FREE delivery Sat, Apr 25",[],[],8K+ bought in past month,None,96.04,wireless headphones
208,"JBL Tune 520BT - Wireless On-Ear Headphones, U...",B0CQ1HP3RX,13697,https://m.media-amazon.com/images/I/61mz7Wxnjd...,39.95,59.95,4.6 out of 5 stars,False,/JBL-Tune-520BT-Ear-Lightweight/dp/B0CQ1HP3RX/...,None,"FREE delivery Sat, Apr 25",[],[],2K+ bought in past month,None,37.95,wireless headphones
209,TAGRY Hybrid Active Noise Cancelling Headphone...,B0GSQL8J2V,149,https://m.media-amazon.com/images/I/71J3F2q7Hu...,59.98,149.99,4.7 out of 5 stars,False,/TAGRY-Cancelling-Headphones-Bluetooth-Headpho...,None,"FREE delivery Sat, Apr 25",[],[],None,None,56.98,wireless headphones
210,"HAOYUYAN Wireless Earbuds, Sports Bluetooth He...",B0GM6J315P,231,https://m.media-amazon.com/images/I/61DzAvRWJl...,23.99,39.99,4.6 out of 5 stars,False,/HAOYUYAN-Bluetooth-Headphones-Waterproof-Runn...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],4K+ bought in past month,None,0.00,wireless headphones
211,JBL Vibe Beam - True Wireless JBL Deep Bass So...,B0BQPNMXQV,36878,https://m.media-amazon.com/images/I/41+1Csr1pS...,29.95,49.95,4.2 out of 5 stars,False,/JBL-Vibe-Beam-Wireless-Headphones/dp/B0BQPNMX...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,27.61,wireless headphones
212,Bose QuietComfort Headphones - Wireless Blueto...,B0DZHR44J9,19250,https://m.media-amazon.com/images/I/51tItfLj8x...,359.00,0.00,4.6 out of 5 stars,False,/Bose-QuietComfort-Bluetooth-Headphones-Cancel...,None,"FREE delivery Tomorrow, Apr 21",[],[],1K+ bought in past month,None,279.99,wireless headphones
213,JBL Vibe Beam 2 - True Wireless Noise Cancelli...,B0DN45YMP6,4396,https://m.media-amazon.com/images/I/618f5yBk26...,NaN,0.00,4.2 out of 5 stars,False,/JBL-Vibe-Beam-Cancelling-Technology/dp/B0DN45...,None,"FREE delivery Sat, Apr 25",[],[],10K+ bought in past month,None,0.00,wireless headphones
214,JBL Tune 770NC - Adaptive Noise Cancelling wit...,B0CT9XTKKM,4761,https://m.media-amazon.com/images/I/51V1bf76cM...,99.95,149.95,4.5 out of 5 stars,False,/JBL-TUNE-770NC-Lightweight-comfortable/dp/B0C...,None,"FREE delivery Sat, Apr 25",[],[],2K+ bought in past month,None,69.00,wireless headphones
215,Bluetooth Headphones with Active Noise Cancell...,B0GLN8R9D7,25,https://m.media-amazon.com/images/I/61O-+3Hbvh...,16.99,19.99,4.3 out of 5 stars,False,/MMWOWARTS-Bluetooth-Headphones-Cancelling-Wir...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],1K+ bought in past month,None,0.00,wireless headphones
216,TOZO A1 Wireless Earbuds Bluetooth 5.3 Light W...,B09FT58QQP,112578,https://m.media-amazon.com/images/I/81+4jNKVFg...,12.31,22.99,4.3 out of 5 stars,False,/A1/dp/B09FT58QQP/ref=sr_1_25?dib=eyJ2IjoiMSJ9...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,0.00,wireless headphones
217,"Apple EarPods Headphones with USB-C Plug, Wire...",B0DCH8VDXF,12303,https://m.media-amazon.com/images/I/513OSdW4el...,19.00,0.00,4.6 out of 5 stars,False,/Apple-EarPods-Headphones-Built-Control/dp/B0D...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,17.10,wireless headphones
218,JBL Tune 510BT - Bluetooth headphones with up ...,B092CP8ZH4,90693,https://m.media-amazon.com/images/I/51Dd8aGSW0...,NaN,0.00,4.5 out of 5 stars,False,/JBL-Tune-510BT-Ear-Headphones/dp/B092CP8ZH4/r...,None,None,[],[],10K+ bought in past month,None,0.00,wireless headphones
219,"Uliptz Wireless Bluetooth Headphones, 65H Play...",B09NNBBY8F,14192,https://m.media-amazon.com/images/I/61-ZTbzw6o...,15.99,19.99,4.6 out of 5 stars,False,/Uliptz-Bluetooth-Headphones-Microphone-Lightw...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,0.00,wireless headphones
220,Beats Studio Pro - Premium Wireless Over-Ear H...,B0FHM61VTK,26990,https://m.media-amazon.com/images/I/61c8vBJoCm...,349.95,0.00,4.5 out of 5 stars,False,/Beats-Studio-Pro-Headphones-Cancelling/dp/B0F...,None,"FREE delivery Sat, Apr 25",[],[],7K+ bought in past month,None,139.28,wireless headphones
221,Avantree Opera - Wireless Headphones for TV Wa...,B08D6GHYD7,5268,https://m.media-amazon.com/images/I/61s3zJjDdt...,149.99,159.99,4.2 out of 5 stars,False,/Avantree-Wireless-Headphones-Transmitter-Blue...,None,"FREE delivery Sat, Apr 25",[],[],None,None,0.00,wireless headphones
222,bmani Ear Buds Wireless Earbuds Bluetooth Head...,B09FLNSYDZ,53452,https://m.media-amazon.com/images/I/71GPFE2yHG...,24.67,39.99,4.4 out of 5 stars,False,/Wireless-Bluetooth-Headphones-Earphones-BMANI...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],10K+ bought in past month,None,23.44,wireless headphones
223,JOYWISE Bluetooth Wireless Headphones 16H Play...,B0BTLVHMHW,3094,https://m.media-amazon.com/images/I/61y8xIywvg...,19.99,27.99,4.4 out of 5 stars,False,/JOYWISE-Bluetooth-Headphones-Earphones-Waterp...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],2K+ bought in past month,None,15.08,wireless headphones

In [76]:
df[["price", "productRating", "category"]].sample(20)

     price       productRating             category
14   19.95  4.8 out of 5 stars           board game
171  25.90  4.7 out of 5 stars         coffee beans
81   17.63  4.7 out of 5 stars           board game
11   24.98  4.8 out of 5 stars           board game
93   19.85  4.7 out of 5 stars           board game
101  20.21  4.6 out of 5 stars         coffee beans
43   14.99  4.7 out of 5 stars           board game
96   28.34  4.5 out of 5 stars         coffee beans
78   53.75  4.8 out of 5 stars           board game
158  38.38  4.6 out of 5 stars         coffee beans
108  17.98  4.4 out of 5 stars         coffee beans
161  14.69  4.5 out of 5 stars         coffee beans
41   19.99  4.7 out of 5 stars           board game
195  44.99  4.6 out of 5 stars  wireless headphones
90   21.99  4.8 out of 5 stars           board game
79   24.99  4.7 out of 5 stars           board game
214  99.95  4.5 out of 5 stars  wireless headphones
159  37.95  4.5 out of 5 stars         coffee beans
203  38.00  4.5 out of 5 stars  wireless headphones
95   44.95  4.7 out of 5 stars           board game

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   productDescription  224 non-null    object
 1   asin                224 non-null    object
 2   countReview         224 non-null    int64
 3   imgUrl              224 non-null    object
 4   price               218 non-null    float64
 5   retailPrice         224 non-null    float64
 6   productRating       223 non-null    object
 7   prime               224 non-null    bool
 8   dpUrl               224 non-null    object
 9   series              0 non-null      object
 10  deliveryMessage     219 non-null    object
 11  variations          224 non-null    object
 12  productDetails      224 non-null    object
 13  salesVolume         219 non-null    object
 14  manufacturer        0 non-null      object
 15  secondaryOffer      224 non-null    float64
 16  category            224 non-null    object
dtypes: bool(1), float64(3), int64(1), object(12)
memory usage: 28.3+ KB

In [78]:
df["productRating"] = (
    df["productRating"]
    .str.extract(r"([0-9.]+)")
    .astype(float)
)

In [79]:
df.sample(20, random_state=42)

,productDescription,asin,countReview,imgUrl,price,retailPrice,productRating,prime,dpUrl,series,deliveryMessage,variations,productDetails,salesVolume,manufacturer,secondaryOffer,category
9,Hasbro Gaming Battleship Classic Board Game | ...,B09D4QRJ8Y,7624,https://m.media-amazon.com/images/I/81PXMzof4N...,16.84,19.99,4.7,False,/Battleship-Classic-Board-Strategy-Players/dp/...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,0.00,board game
84,Mouse Trap Board Game For Kids Ages 6 and Up (...,B00000DMFD,9324,https://m.media-amazon.com/images/I/81imYb-vUp...,24.99,0.00,4.6,False,/Mouse-Trap-Game-Amazon-Exclusive/dp/B00000DMF...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],1K+ bought in past month,None,0.00,board game
117,"Starbucks Whole Coffee Beans, Medium Roast Hot...",B07LFSNK9M,1837,https://m.media-amazon.com/images/I/8145WujhgP...,30.42,32.07,4.7,False,/Starbucks-Medium-Coffee-Variety-12-oz/dp/B07L...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],800+ bought in past month,None,0.00,coffee beans
144,"365 by Whole Foods Market, Pleasant Morning Bu...",B074XXNDRC,1838,https://m.media-amazon.com/images/I/61qfanxE-f...,18.48,0.00,4.2,False,/365-Whole-Foods-Market-Medium-Dark/dp/B074XXN...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],2K+ bought in past month,None,0.00,coffee beans
221,Avantree Opera - Wireless Headphones for TV Wa...,B08D6GHYD7,5268,https://m.media-amazon.com/images/I/61s3zJjDdt...,149.99,159.99,4.2,False,/Avantree-Wireless-Headphones-Transmitter-Blue...,None,"FREE delivery Sat, Apr 25",[],[],None,None,0.00,wireless headphones
113,"Copper Moon Dark Roast Whole Bean Coffee, Suma...",B01L9YE808,5818,https://m.media-amazon.com/images/I/71PI8ZHsSw...,21.49,0.00,4.4,False,/Copper-Moon-Sumatra-Smoothly-Full-Bodied/dp/B...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],7K+ bought in past month,None,0.00,coffee beans
68,Spooktacular Board Game – Play as 20 Spooky Ci...,B0F16HLC5P,18,https://m.media-amazon.com/images/I/716aHggtCv...,59.99,0.00,4.7,False,/Spooktacular-Board-Game-Monsters-Strategy/dp/...,None,"FREE delivery Sat, Apr 25",[],[],50+ bought in past month,None,0.00,board game
104,Amazon Fresh Organic Fair Trade Sumatra Whole ...,B072MQFGHG,1863,https://m.media-amazon.com/images/I/81VE86P+G1...,6.98,0.00,4.2,False,/AmazonFresh-Organic-Trade-Sumatra-Coffee/dp/B...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,0.00,coffee beans
177,"Tony's Coffee, Cafe Carmelita (12oz), Medium R...",B01I93B9GI,148,https://m.media-amazon.com/images/I/61kn2JnLg2...,NaN,0.00,4.6,False,/Tonys-Coffee-Cafe-Carmelita-Whole/dp/B01I93B9...,None,None,[],[],200+ bought in past month,None,18.50,coffee beans
185,"365 by Whole Foods Market, Island Blend Whole ...",B074H81M7Y,478,https://m.media-amazon.com/images/I/61hoFRHIL3...,18.48,0.00,4.5,False,/365-Whole-Foods-Market-Medium-Light/dp/B074H8...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],700+ bought in past month,None,0.00,coffee beans
55,The Night Cage by Smirk and Dagger | Cooperati...,B08ZSK752P,879,https://m.media-amazon.com/images/I/61KfSCGnpB...,38.52,44.99,4.7,False,/Smirk-Dagger-The-Night-Cage/dp/B08ZSK752P/ref...,None,"FREE delivery Sat, Apr 25",[],[],200+ bought in past month,None,32.22,board game
15,Taco Cat Goat Cheese Pizza Wildly Entertaining...,B077Z1R28P,53337,https://m.media-amazon.com/images/I/61L3JcwfsD...,8.10,9.99,4.8,False,/Taco-Cat-Goat-Cheese-Pizza/dp/B077Z1R28P/ref=...,None,FREE delivery Apr 22 - 24,[],[],10K+ bought in past month,None,0.00,board game
199,Sony WH-CH520 Wireless Headphones Bluetooth On...,B0BS1RT9S2,31333,https://m.media-amazon.com/images/I/41JACWT-wW...,38.00,69.99,4.5,False,/Sony-WH-CH520-Headphones-Bluetooth-Microphone...,None,"FREE delivery Sat, Apr 25",[],[],4K+ bought in past month,None,32.43,wireless headphones
25,Secret Hitler,B01JKD4HYC,15015,https://m.media-amazon.com/images/I/51FQfTXB+H...,45.00,0.00,4.9,False,/Secret-Hitler/dp/B01JKD4HYC/ref=sr_1_26?dib=e...,None,"FREE delivery Sat, Apr 25",[],[],3K+ bought in past month,None,0.00,board game
30,"Hasbro® Don’t Break The Ice Game, Classic Vers...",B01MS6B7BV,18044,https://m.media-amazon.com/images/I/81KhN-wJEW...,17.35,19.99,4.8,False,/Dont-Break-the-Ice-Game/dp/B01MS6B7BV/ref=sr_...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,0.00,board game
45,Lucky Egg Official Grab The Mic – Family Karao...,B0CWVMNNFV,3979,https://m.media-amazon.com/images/I/71lzGgv9hk...,19.99,0.00,4.7,False,/Lucky-Egg-Exciting-Grab-Mic/dp/B0CWVMNNFV/ref...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],7K+ bought in past month,None,0.00,board game
171,"Lavazza Espresso Whole Bean Coffee, Medium Roa...",B016RY0LWO,6804,https://m.media-amazon.com/images/I/61DZrxomt+...,25.90,0.00,4.7,False,/Lavazza-Espresso-Coffee-Medium-2-2-Pound/dp/B...,None,"FREE delivery Mon, Apr 27",[],[],10K+ bought in past month,None,24.00,coffee beans
82,Asmodee HEAT: Pedal to the Metal Board Game - ...,B0BGXPZG4B,924,https://m.media-amazon.com/images/I/91v-6pjK0Z...,67.49,74.99,4.8,False,/Strategy-Players-Playtime-Days-Wonder/dp/B0BG...,None,"FREE delivery Sat, Apr 25",[],[],500+ bought in past month,None,61.42,board game
208,"JBL Tune 520BT - Wireless On-Ear Headphones, U...",B0CQ1HP3RX,13697,https://m.media-amazon.com/images/I/61mz7Wxnjd...,39.95,59.95,4.6,False,/JBL-Tune-520BT-Ear-Lightweight/dp/B0CQ1HP3RX/...,None,"FREE delivery Sat, Apr 25",[],[],2K+ bought in past month,None,37.95,wireless headphones
97,"Amazon Fresh, Colombia Whole Bean Coffee Mediu...",B071WWCVJV,11459,https://m.media-amazon.com/images/I/7121M8H6is...,18.37,0.00,4.3,False,/AmazonFresh-Colombia-Whole-Coffee-Medium/dp/B...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],20K+ bought in past month,None,0.00,coffee beans

In [81]:
df.sample(20, random_state=42)

,productDescription,asin,countReview,imgUrl,price,retailPrice,productRating,prime,dpUrl,series,deliveryMessage,variations,productDetails,salesVolume,manufacturer,secondaryOffer,category
9,Hasbro Gaming Battleship Classic Board Game | ...,B09D4QRJ8Y,7624,https://m.media-amazon.com/images/I/81PXMzof4N...,16.84,19.99,4.7,False,/Battleship-Classic-Board-Strategy-Players/dp/...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,0.00,board game
84,Mouse Trap Board Game For Kids Ages 6 and Up (...,B00000DMFD,9324,https://m.media-amazon.com/images/I/81imYb-vUp...,24.99,0.00,4.6,False,/Mouse-Trap-Game-Amazon-Exclusive/dp/B00000DMF...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],1K+ bought in past month,None,0.00,board game
117,"Starbucks Whole Coffee Beans, Medium Roast Hot...",B07LFSNK9M,1837,https://m.media-amazon.com/images/I/8145WujhgP...,30.42,32.07,4.7,False,/Starbucks-Medium-Coffee-Variety-12-oz/dp/B07L...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],800+ bought in past month,None,0.00,coffee beans
144,"365 by Whole Foods Market, Pleasant Morning Bu...",B074XXNDRC,1838,https://m.media-amazon.com/images/I/61qfanxE-f...,18.48,0.00,4.2,False,/365-Whole-Foods-Market-Medium-Dark/dp/B074XXN...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],2K+ bought in past month,None,0.00,coffee beans
221,Avantree Opera - Wireless Headphones for TV Wa...,B08D6GHYD7,5268,https://m.media-amazon.com/images/I/61s3zJjDdt...,149.99,159.99,4.2,False,/Avantree-Wireless-Headphones-Transmitter-Blue...,None,"FREE delivery Sat, Apr 25",[],[],None,None,0.00,wireless headphones
113,"Copper Moon Dark Roast Whole Bean Coffee, Suma...",B01L9YE808,5818,https://m.media-amazon.com/images/I/71PI8ZHsSw...,21.49,0.00,4.4,False,/Copper-Moon-Sumatra-Smoothly-Full-Bodied/dp/B...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],7K+ bought in past month,None,0.00,coffee beans
68,Spooktacular Board Game – Play as 20 Spooky Ci...,B0F16HLC5P,18,https://m.media-amazon.com/images/I/716aHggtCv...,59.99,0.00,4.7,False,/Spooktacular-Board-Game-Monsters-Strategy/dp/...,None,"FREE delivery Sat, Apr 25",[],[],50+ bought in past month,None,0.00,board game
104,Amazon Fresh Organic Fair Trade Sumatra Whole ...,B072MQFGHG,1863,https://m.media-amazon.com/images/I/81VE86P+G1...,6.98,0.00,4.2,False,/AmazonFresh-Organic-Trade-Sumatra-Coffee/dp/B...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,0.00,coffee beans
177,"Tony's Coffee, Cafe Carmelita (12oz), Medium R...",B01I93B9GI,148,https://m.media-amazon.com/images/I/61kn2JnLg2...,NaN,0.00,4.6,False,/Tonys-Coffee-Cafe-Carmelita-Whole/dp/B01I93B9...,None,None,[],[],200+ bought in past month,None,18.50,coffee beans
185,"365 by Whole Foods Market, Island Blend Whole ...",B074H81M7Y,478,https://m.media-amazon.com/images/I/61hoFRHIL3...,18.48,0.00,4.5,False,/365-Whole-Foods-Market-Medium-Light/dp/B074H8...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],700+ bought in past month,None,0.00,coffee beans
55,The Night Cage by Smirk and Dagger | Cooperati...,B08ZSK752P,879,https://m.media-amazon.com/images/I/61KfSCGnpB...,38.52,44.99,4.7,False,/Smirk-Dagger-The-Night-Cage/dp/B08ZSK752P/ref...,None,"FREE delivery Sat, Apr 25",[],[],200+ bought in past month,None,32.22,board game
15,Taco Cat Goat Cheese Pizza Wildly Entertaining...,B077Z1R28P,53337,https://m.media-amazon.com/images/I/61L3JcwfsD...,8.10,9.99,4.8,False,/Taco-Cat-Goat-Cheese-Pizza/dp/B077Z1R28P/ref=...,None,FREE delivery Apr 22 - 24,[],[],10K+ bought in past month,None,0.00,board game
199,Sony WH-CH520 Wireless Headphones Bluetooth On...,B0BS1RT9S2,31333,https://m.media-amazon.com/images/I/41JACWT-wW...,38.00,69.99,4.5,False,/Sony-WH-CH520-Headphones-Bluetooth-Microphone...,None,"FREE delivery Sat, Apr 25",[],[],4K+ bought in past month,None,32.43,wireless headphones
25,Secret Hitler,B01JKD4HYC,15015,https://m.media-amazon.com/images/I/51FQfTXB+H...,45.00,0.00,4.9,False,/Secret-Hitler/dp/B01JKD4HYC/ref=sr_1_26?dib=e...,None,"FREE delivery Sat, Apr 25",[],[],3K+ bought in past month,None,0.00,board game
30,"Hasbro® Don’t Break The Ice Game, Classic Vers...",B01MS6B7BV,18044,https://m.media-amazon.com/images/I/81KhN-wJEW...,17.35,19.99,4.8,False,/Dont-Break-the-Ice-Game/dp/B01MS6B7BV/ref=sr_...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],5K+ bought in past month,None,0.00,board game
45,Lucky Egg Official Grab The Mic – Family Karao...,B0CWVMNNFV,3979,https://m.media-amazon.com/images/I/71lzGgv9hk...,19.99,0.00,4.7,False,/Lucky-Egg-Exciting-Grab-Mic/dp/B0CWVMNNFV/ref...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],7K+ bought in past month,None,0.00,board game
171,"Lavazza Espresso Whole Bean Coffee, Medium Roa...",B016RY0LWO,6804,https://m.media-amazon.com/images/I/61DZrxomt+...,25.90,0.00,4.7,False,/Lavazza-Espresso-Coffee-Medium-2-2-Pound/dp/B...,None,"FREE delivery Mon, Apr 27",[],[],10K+ bought in past month,None,24.00,coffee beans
82,Asmodee HEAT: Pedal to the Metal Board Game - ...,B0BGXPZG4B,924,https://m.media-amazon.com/images/I/91v-6pjK0Z...,67.49,74.99,4.8,False,/Strategy-Players-Playtime-Days-Wonder/dp/B0BG...,None,"FREE delivery Sat, Apr 25",[],[],500+ bought in past month,None,61.42,board game
208,"JBL Tune 520BT - Wireless On-Ear Headphones, U...",B0CQ1HP3RX,13697,https://m.media-amazon.com/images/I/61mz7Wxnjd...,39.95,59.95,4.6,False,/JBL-Tune-520BT-Ear-Lightweight/dp/B0CQ1HP3RX/...,None,"FREE delivery Sat, Apr 25",[],[],2K+ bought in past month,None,37.95,wireless headphones
97,"Amazon Fresh, Colombia Whole Bean Coffee Mediu...",B071WWCVJV,11459,https://m.media-amazon.com/images/I/7121M8H6is...,18.37,0.00,4.3,False,/AmazonFresh-Colombia-Whole-Coffee-Medium/dp/B...,None,"FREE delivery Sat, Apr 25 on $35 of items ship...",[],[],20K+ bought in past month,None,0.00,coffee beans

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   productDescription  224 non-null    object
 1   asin                224 non-null    object
 2   countReview         224 non-null    int64
 3   imgUrl              224 non-null    object
 4   price               218 non-null    float64
 5   retailPrice         224 non-null    float64
 6   productRating       223 non-null    float64
 7   prime               224 non-null    bool
 8   dpUrl               224 non-null    object
 9   series              0 non-null      object
 10  deliveryMessage     219 non-null    object
 11  variations          224 non-null    object
 12  productDetails      224 non-null    object
 13  salesVolume         219 non-null    object
 14  manufacturer        0 non-null      object
 15  secondaryOffer      224 non-null    float64
 16  category            224 non-null    object
dtypes: bool(1), float64(4), int64(1), object(11)
memory usage: 28.3+ KB

In [83]:
df["productRating"].head(10)

0    4.8
1    4.8
2    4.8
3    4.7
4    4.8
5    4.8
6    4.8
7    4.7
8    4.8
9    4.7
Name: productRating, dtype: float64

In [84]:
df["productRating"].dtype

dtype('float64')

In [85]:
df["productRating"].isnull().sum()

np.int64(1)

In [86]:
def data_check(df):
    print("SHAPE:", df.shape)
    print("\nNULLS:\n", df.isnull().sum().sort_values(ascending=False).head(10))
    print("\nDTYPES:\n", df.dtypes)

data_check(df)

SHAPE: (224, 17)

NULLS:
 manufacturer          224
series                224
price                   6
deliveryMessage         5
salesVolume             5
productRating           1
productDescription      0
secondaryOffer          0
productDetails          0
variations              0
dtype: int64

DTYPES:
 productDescription     object
asin                   object
countReview             int64
imgUrl                 object
price                 float64
retailPrice           float64
productRating         float64
prime                    bool
dpUrl                  object
series                 object
deliveryMessage        object
variations             object
productDetails         object
salesVolume            object
manufacturer           object
secondaryOffer        float64
category               object
dtype: object

In [87]:
df["salesVolume"].sample(20, random_state=42)

9       5K+ bought in past month
84      1K+ bought in past month
117    800+ bought in past month
144     2K+ bought in past month
221                         None
113     7K+ bought in past month
68      50+ bought in past month
104     5K+ bought in past month
177    200+ bought in past month
185    700+ bought in past month
55     200+ bought in past month
15     10K+ bought in past month
199     4K+ bought in past month
25      3K+ bought in past month
30      5K+ bought in past month
45      7K+ bought in past month
171    10K+ bought in past month
82     500+ bought in past month
208     2K+ bought in past month
97     20K+ bought in past month
Name: salesVolume, dtype: object

In [88]:
def clean_sales_volume(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x).upper()
    
    num = ""
    for char in x:
        if char.isdigit():
            num += char
        elif char == ".":
            num += char
        elif num:
            break 
    
    if num == "":
        return np.nan
    
    value = float(num)
    
   
    if "K" in x:
        value = value * 1000
    
    return value

In [89]:
df["salesVolume"].sample(20, random_state=42)

9       5K+ bought in past month
84      1K+ bought in past month
117    800+ bought in past month
144     2K+ bought in past month
221                         None
113     7K+ bought in past month
68      50+ bought in past month
104     5K+ bought in past month
177    200+ bought in past month
185    700+ bought in past month
55     200+ bought in past month
15     10K+ bought in past month
199     4K+ bought in past month
25      3K+ bought in past month
30      5K+ bought in past month
45      7K+ bought in past month
171    10K+ bought in past month
82     500+ bought in past month
208     2K+ bought in past month
97     20K+ bought in past month
Name: salesVolume, dtype: object

In [90]:
df["salesVolume_clean"] = df["salesVolume"].apply(clean_sales_volume)

In [91]:
df[["salesVolume", "salesVolume_clean"]].sample(20, random_state=42)

                   salesVolume  salesVolume_clean
9     5K+ bought in past month             5000.0
84    1K+ bought in past month             1000.0
117  800+ bought in past month              800.0
144   2K+ bought in past month             2000.0
221                       None                NaN
113   7K+ bought in past month             7000.0
68    50+ bought in past month               50.0
104   5K+ bought in past month             5000.0
177  200+ bought in past month              200.0
185  700+ bought in past month              700.0
55   200+ bought in past month              200.0
15   10K+ bought in past month            10000.0
199   4K+ bought in past month             4000.0
25    3K+ bought in past month             3000.0
30    5K+ bought in past month             5000.0
45    7K+ bought in past month             7000.0
171  10K+ bought in past month            10000.0
82   500+ bought in past month              500.0
208   2K+ bought in past month             2000.0
97   20K+ bought in past month            20000.0

In [92]:
df["salesVolume_clean"].isnull().sum()

np.int64(6)

In [93]:
df["salesVolume_clean"].describe()

count      218.000000
mean      4532.798165
std       7559.922827
min         50.000000
25%       1000.000000
50%       2000.000000
75%       6000.000000
max      80000.000000
Name: salesVolume_clean, dtype: float64

In [94]:
df["price"] = pd.to_numeric(df["price"], errors="coerce")

In [95]:
df["price"].isnull().sum()
df["price"].dtype

dtype('float64')

In [96]:
df["productRating"] = pd.to_numeric(df["productRating"], errors="coerce")

In [97]:
df["productRating"].dtype
df["productRating"].isnull().sum()

np.int64(1)

In [98]:
df["productRating"] = pd.to_numeric(df["productRating"], errors="coerce")

In [99]:
df["productRating"].dtype

dtype('float64')

In [100]:
df["productRating"].isnull().sum()

np.int64(1)

In [101]:
df["productRating"].sample(10)

40     4.7
6      4.8
104    4.2
164    4.7
63     4.7
62     4.8
23     4.7
133    4.6
101    4.6
48     4.5
Name: productRating, dtype: float64

In [102]:
df["price_tier"] = pd.qcut(
    df["price"],
    q=3,
    labels=["budget", "mid", "premium"]
)

In [103]:
df["price_tier"].value_counts()

price_tier
budget     73
premium    73
mid        72
Name: count, dtype: int64

In [104]:
df["has_reviews"] = df["countReview"] > 0

In [105]:
df["review_density"] = df["countReview"] / (df["productRating"] + 0.01)

In [106]:
df.columns

Index(['productDescription', 'asin', 'countReview', 'imgUrl', 'price',
       'retailPrice', 'productRating', 'prime', 'dpUrl', 'series',
       'deliveryMessage', 'variations', 'productDetails', 'salesVolume',
       'manufacturer', 'secondaryOffer', 'category', 'salesVolume_clean',
       'price_tier', 'has_reviews', 'review_density'],
      dtype='object')

In [107]:
df[["price", "price_tier", "countReview", "has_reviews", "review_density"]].sample(10, random_state=42)

      price price_tier  countReview  has_reviews  review_density
9     16.84     budget         7624         True     1618.683652
84    24.99        mid         9324         True     2022.559653
117   30.42        mid         1837         True      390.021231
144   18.48     budget         1838         True      436.579572
221  149.99    premium         5268         True     1251.306413
113   21.49        mid         5818         True     1319.274376
68    59.99    premium           18         True        3.821656
104    6.98     budget         1863         True      442.517815
177     NaN        NaN          148         True       32.104121
185   18.48     budget          478         True      105.986696

In [108]:
df["price_tier"].value_counts()

price_tier
budget     73
premium    73
mid        72
Name: count, dtype: int64

In [109]:
df["has_reviews"].value_counts()

has_reviews
True     223
False      1
Name: count, dtype: int64

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   productDescription  224 non-null    object
 1   asin                224 non-null    object
 2   countReview         224 non-null    int64
 3   imgUrl              224 non-null    object
 4   price               218 non-null    float64
 5   retailPrice         224 non-null    float64
 6   productRating       223 non-null    float64
 7   prime               224 non-null    bool
 8   dpUrl               224 non-null    object
 9   series              0 non-null      object
 10  deliveryMessage     219 non-null    object
 11  variations          224 non-null    object
 12  productDetails      224 non-null    object
 13  salesVolume         219 non-null    object
 14  manufacturer        0 non-null      object
 15  secondaryOffer      224 non-null    float64
 16  category            224 non-null    object
 17  salesVolume_clean   218 non-null    float64
 18  price_tier          218 non-null    category
 19  has_reviews         224 non-null    bool
 20  review_density      223 non-null    float64
dtypes: bool(2), category(1), float64(6), int64(1), object(11)
memory usage: 32.4+ KB

In [111]:
df_raw = df.copy()

In [112]:
df_final = df.copy()

In [113]:
df_final = df_final[[
    "asin",
    "productDescription",
    "category",
    "price",
    "retailPrice",
    "productRating",
    "countReview",
    "salesVolume_clean",
    "price_tier",
    "has_reviews",
    "review_density",
    "prime"
]]

In [114]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   asin                224 non-null    object
 1   productDescription  224 non-null    object
 2   category            224 non-null    object
 3   price               218 non-null    float64
 4   retailPrice         224 non-null    float64
 5   productRating       223 non-null    float64
 6   countReview         224 non-null    int64
 7   salesVolume_clean   218 non-null    float64
 8   price_tier          218 non-null    category
 9   has_reviews         224 non-null    bool
 10  review_density      223 non-null    float64
 11  prime               224 non-null    bool
dtypes: bool(2), category(1), float64(5), int64(1), object(3)
memory usage: 16.7+ KB

In [115]:
df_final.sample(10, random_state=42)

,asin,productDescription,category,price,retailPrice,productRating,countReview,salesVolume_clean,price_tier,has_reviews,review_density,prime
9,B09D4QRJ8Y,Hasbro Gaming Battleship Classic Board Game | ...,board game,16.84,19.99,4.7,7624,5000.0,budget,True,1618.683652,False
84,B00000DMFD,Mouse Trap Board Game For Kids Ages 6 and Up (...,board game,24.99,0.00,4.6,9324,1000.0,mid,True,2022.559653,False
117,B07LFSNK9M,"Starbucks Whole Coffee Beans, Medium Roast Hot...",coffee beans,30.42,32.07,4.7,1837,800.0,mid,True,390.021231,False
144,B074XXNDRC,"365 by Whole Foods Market, Pleasant Morning Bu...",coffee beans,18.48,0.00,4.2,1838,2000.0,budget,True,436.579572,False
221,B08D6GHYD7,Avantree Opera - Wireless Headphones for TV Wa...,wireless headphones,149.99,159.99,4.2,5268,NaN,premium,True,1251.306413,False
113,B01L9YE808,"Copper Moon Dark Roast Whole Bean Coffee, Suma...",coffee beans,21.49,0.00,4.4,5818,7000.0,mid,True,1319.274376,False
68,B0F16HLC5P,Spooktacular Board Game – Play as 20 Spooky Ci...,board game,59.99,0.00,4.7,18,50.0,premium,True,3.821656,False
104,B072MQFGHG,Amazon Fresh Organic Fair Trade Sumatra Whole ...,coffee beans,6.98,0.00,4.2,1863,5000.0,budget,True,442.517815,False
177,B01I93B9GI,"Tony's Coffee, Cafe Carmelita (12oz), Medium R...",coffee beans,NaN,0.00,4.6,148,200.0,NaN,True,32.104121,False
185,B074H81M7Y,"365 by Whole Foods Market, Island Blend Whole ...",coffee beans,18.48,0.00,4.5,478,700.0,budget,True,105.986696,False

In [116]:
df_final.to_csv("clean_amazon_products.csv", index=False)

In [4]:
import requests
import pandas as pd
import time

In [6]:
import pandas as pd

df_final = pd.read_csv(r"C:\Users\user\Desktop\Data_Analytics_Project2\Data files(CSVs)\clean_amazon_products.csv")

In [7]:
df_final.head()
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   asin                224 non-null    object
 1   productDescription  224 non-null    object
 2   category            224 non-null    object
 3   price               218 non-null    float64
 4   retailPrice         224 non-null    float64
 5   productRating       223 non-null    float64
 6   countReview         224 non-null    int64
 7   salesVolume_clean   218 non-null    float64
 8   price_tier          218 non-null    object
 9   has_reviews         224 non-null    bool
 10  review_density      223 non-null    float64
 11  prime               224 non-null    bool
dtypes: bool(2), float64(5), int64(1), object(4)
memory usage: 18.1+ KB

In [8]:
df_final[["category", "price", "price_tier"]].sample(10)

         category  price price_tier
22     board game  19.99        mid
158  coffee beans  38.38    premium
118  coffee beans  21.95        mid
186  coffee beans  33.95    premium
178  coffee beans  11.99     budget
173  coffee beans  19.99        mid
10     board game   7.97     budget
88     board game  20.99        mid
44     board game  34.39    premium
95     board game  44.95    premium

In [9]:
df_final["category"] = (
    df_final["category"]
    .str.strip()
    .str.lower()
)

In [10]:
df_final["price_tier"] = df_final.groupby("category")["price"].transform(
    lambda x: pd.qcut(
        x,
        q=3,
        labels=["budget", "mid", "premium"],
        duplicates="drop"
    )
)

In [11]:
df_final[["category", "price", "price_tier"]].sample(15, random_state=42)

                category   price price_tier
9             board game   16.84     budget
84            board game   24.99        mid
117         coffee beans   30.42    premium
144         coffee beans   18.48     budget
221  wireless headphones  149.99    premium
113         coffee beans   21.49        mid
68            board game   59.99    premium
104         coffee beans    6.98     budget
177         coffee beans     NaN        NaN
185         coffee beans   18.48     budget
55            board game   38.52    premium
15            board game    8.10     budget
199  wireless headphones   38.00        mid
25            board game   45.00    premium
30            board game   17.35     budget

In [13]:
df_final["price_tier"].isnull().sum()

np.int64(6)

In [14]:
df_final["price_tier"] = df_final["price_tier"].astype("category")

In [15]:
df_final.to_csv("amazon_products_clean_v2.csv", index=False)